### ISSUE TITLE
is Map::clear() supposed to do drop()?

### ISSUE THREAD

**Issue by yegor256** [yegor256/micromap#102]
At the moment, we don't `drop()` the keys/values. Maybe we should when we clear the map?

**Comment by alexkazik** [comment]
Definitley.

If the clears_it_up test is changed to String (instead of str) then miri tells you:
```
error: memory leaked: alloc47704 (Rust heap, size: 3, align: 1), allocated here:
```

**Comment by yegor256** [comment]
@alexkazik maybe you can contribute with a pull request?
