### ISSUE TITLE
get rid of Clone trait for V and K wherewer possible

### ISSUE THREAD

**Issue by Zefick** [yegor256/micromap#104]
Cloning is not required for the core functionality of `micromap` as well as for `HashMap`, and this restriction can be removed from the many implementation blocks. The `Clone` constraint can be added separately for functions that really need it. E.g. that's how remove_entry's declaration may look like:
```Rust
pub fn remove_entry<Q: PartialEq + ?Sized>(&mut self, k: &Q) -> Option<(K, V)>
where
    K: Borrow<Q> + Clone,
    V: Clone,
{
    ...
}
```
It's only function in the main block that need `Clone`, but I believe it's possible to remove it from there too although this is not necessary.

Impl blocks like `IntoIterator for &Map` and `Clone for Map` must declare its own constraint if it needed. They actually do it anyway and there is no need to change anything there.

If K or V not deriving `Clone` then it will not be possible to call `into_iter()` and `clone()` but all other methods shoud work.

In fact, standard `HashMap` are not required `Clone` for `into_iter()` neither it to be called by reference nor by value and it is the difference between it and the `micromap`. `IntoIterator` for `&HashMap` returns references to its elements and `IntoIterator` for `HashMap` just comsumes a map so it's not accessible anymore.

**Comment by yegor256** [comment]
fixed
