### ISSUE TITLE
Map::remove_entry() is not implemented

### ISSUE THREAD

**Issue by yegor256** [yegor256/micromap#12]
Let's implement it similar to this: https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.remove_entry

**Comment by VsevolodGus** [comment]
isn`t this issue solved?

this implementations is from the branch master
https://github.com/yegor256/micromap/blob/master/src/map.rs#L270

**Comment by yegor256** [comment]
@VsevolodGus yes, closing
