### ISSUE TITLE
Add `heapless` benchmark comparison

### ISSUE THREAD

**Issue by pinkforest** [yegor256/micromap#121]
- https://crates.io/crates/heapless provides [heapless::IndexMap](https://japaric.github.io/heapless/heapless/struct.IndexMap.html)  and IndexSet

**Comment by yegor256** [comment]
@pinkforest good idea! can you please submit a PR?

**Comment by pinkforest** [comment]
PR's up
- #123

**Comment by yegor256** [comment]
@pinkforest looks like we are losing :) any idea, how to fix this?

**Comment by pinkforest** [comment]
heapless uses [buffer](https://github.com/japaric/heapless/blob/main/src/linear_map.rs#L182) via it's [stack Vec](https://github.com/japaric/heapless/blob/main/src/vec.rs) for all of it's `insert()`

Side note: It also uses safe `mem::swap` to find / replace existing but that doesn't affect this bench

e.g.
```rust
pub fn insert(&mut self, key: K, mut value: V) {
        if let Some((_, v)) = self.iter_mut().find(|&(k, _)| *k == key) {
            mem::swap(v, &mut value);
            return;
        }
        let target = self.next;
        self.pairs[target].write(Some((key, value)));
        if target == self.next {
            self.next += 1;
        }
    }
```
Side note 2: heapless also provides `Result<T, E>` as it's fallible
