### ISSUE TITLE
serde dependency should be optional

### ISSUE THREAD

**Issue by DCNick3** [yegor256/micromap#16]
Serde dependency is not really necessary for the functionality of the crate, only adding serialization capabilities. A common practice is to make it an optional dependency (see, for example, `gram-rs` [here](https://github.com/bitshifter/glam-rs/blob/063b327ab69225e263b35efb6a4fcd04cd080489/Cargo.toml#L49) and [here](https://github.com/bitshifter/glam-rs/blob/063b327ab69225e263b35efb6a4fcd04cd080489/src/features.rs#L14))

**Comment by yegor256** [comment]
@DCNick3 good point! Can you please submit a pull request?

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.7`

**Comment by yegor256** [comment]
@DCNick3 it's fixed and released
