### ISSUE TITLE
get rid of the Copy trait for K and V

### ISSUE THREAD

**Issue by yegor256** [yegor256/micromap#18]
Somehow `Vec` and `HashMap` work with keys and values that don't implement `Copy`. We should do the same. I'm not sure exactly how this can be done, but it should be possible.

**Comment by WiebeCnossen** [comment]
I am not sure this would have great value for `micromap`: it is meant to use the stack whereas `Vec` and `HashMap` are intended to use the heap. Using `micromap` with types that do not implement `Copy` would probably be an unusual case.

Also depending on how far you want to take this issue (concretely: remove `Clone` as well), this would have an impact on the current API as e.g. `.into_iter(&self)` really cannot do without this.

**Comment by yegor256** [comment]
@WiebeCnossen I'm not really an expert in this area. Help me understand. Now, when we put a pair into the array, we do `memcpy`. If we use `Clone`, we will put pointers into our array? Is this your concern?

**Comment by yegor256** [comment]
we don't use `Copy` anymore
