### ISSUE TITLE
Using swap deletion to maintain 'packed' array

### ISSUE THREAD

**Issue by WiebeCnossen** [yegor256/micromap#23]
The current implementation requires to loop over empty slots. The code could be simpler - and depending on the use case faster - if the last pair would be moved to the empty slot on deletion and empty slots would never occur in the range `0..self.next`.

For instance the implementation of `len(&self)` would reduce to `self.next` (therefore I would suggest renaming `next` to `len` if this adjustment would be made).

**Comment by yegor256** [comment]
@WiebeCnossen good idea, let's do it

**Comment by yegor256** [comment]
@WiebeCnossen this is implemented in 0.0.15
