### ISSUE TITLE
Possible Undefined Behavior with `Map::new` in safe Rust

### ISSUE THREAD

**Issue by cafce25** [yegor256/micromap#69]
As it's currently written the new in `src/ctors.rs` can lead to undefined behavior in safe Rust. You can invoke it with the following test:
```rust
#[test]
fn undefined() {
    let _m: Map<Vec<u8>, u8, 1> = Map::new();
}
```

I'm either getting a `SIGILL` or `SIGSEGV` depending on the actual conditions when running tests in release with
```
cargo test --release -- ctors::undefined
```

**Comment by yegor256** [comment]
@cafce25 by any chance, do you know how to solve this?

**Comment by yegor256** [comment]
@cafce25 in the meantime, I introduced a fix (0c81995), per this recommendation: https://stackoverflow.com/a/76091714/187141 However, the performance degraded because of this fix :(

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.9`

**Comment by cafce25** [comment]
I think `MaybeUninit<Pair>` is the fix, but you might want to
1. use `MaybeUninit::write` instead of creating i.e. replace
    ```rust
    self.pairs[i] = MaybeUninit::new(Absent);
    ```
    with
    ```rust
    self.pairs[i].write(Absent)
    ```
2. run your benchmarks in release mode `cargo test --release -- --test benchmark --nocapture` (might need some adjustments to ensure the actual usages aren't optimized away but will give more realistic numbers)

**Comment by yegor256** [comment]
@cafce25 thanks, I replaced assignments with `write`, as you suggested. Also, we run benchmarking scripts in `release` mode, see: https://github.com/yegor256/micromap/blob/master/rebuild_benchmark.sh#L21-L22

**Comment by cafce25** [comment]
I see, I only read `tests/benchmark.rs` and it suggests `cargo test` without `--release`
